# Generated by Django 4.2.3 on 2023-09-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('guests', models.PositiveIntegerField(choices=[(1, '1 guest'), (2, '2 guests'), (3, '3 guests'), (4, '4 guests'), (5, '5 guests')])),
                ('room_type', models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC'), ('Single Bed', 'Single Bed'), ('Double Bed', 'Double Bed')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='destinations')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc1', models.TextField()),
                ('desc2', models.TextField()),
                ('img', models.ImageField(upload_to='dynamic')),
                ('img1', models.ImageField(upload_to='dynamic')),
                ('img2', models.ImageField(upload_to='dynamic')),
                ('img3', models.ImageField(upload_to='dynamic')),
                ('img4', models.ImageField(upload_to='dynamic')),
                ('img5', models.ImageField(upload_to='dynamic')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='hotel')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='packages')),
                ('img1', models.ImageField(upload_to='packages')),
                ('desc', models.TextField()),
                ('desc1', models.TextField()),
                ('price', models.IntegerField()),
                ('price1', models.IntegerField()),
            ],
        ),
    ]
