# Generated by Django 4.2.3 on 2023-09-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc1', models.TextField()),
                ('desc2', models.TextField()),
                ('img', models.ImageField(upload_to='package1')),
                ('img1', models.ImageField(upload_to='package1')),
            ],
        ),
        migrations.CreateModel(
            name='Package2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc1', models.TextField()),
                ('desc2', models.TextField()),
                ('desc3', models.TextField()),
                ('img', models.ImageField(upload_to='package2')),
                ('img1', models.ImageField(upload_to='package2')),
                ('img2', models.ImageField(upload_to='package2')),
            ],
        ),
    ]
