# Generated by Django 4.2.3 on 2023-09-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_package1_package2'),
    ]

    operations = [
        migrations.AddField(
            model_name='package2',
            name='hoteldesc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package2',
            name='hotelimg',
            field=models.ImageField(default=0, upload_to='package2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package2',
            name='hotelname',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package2',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
