# Generated by Django 4.2.3 on 2023-09-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_package2_hoteldesc_package2_hotelimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package1',
            name='hoteldesc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package1',
            name='hotelimg',
            field=models.ImageField(default=0, upload_to='package1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package1',
            name='hotelname',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package1',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
