# Generated by Django 4.2.3 on 2023-09-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_package1_hoteldesc_package1_hotelimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='pkg1',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dynamic',
            name='pkg2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dynamic',
            name='price1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dynamic',
            name='price2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
