# Generated by Django 4.2.3 on 2023-09-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0005_dynamic_pkg1_dynamic_pkg2_dynamic_price1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package1',
        ),
        migrations.RemoveField(
            model_name='dynamic',
            name='pkg1',
        ),
        migrations.RemoveField(
            model_name='dynamic',
            name='pkg2',
        ),
        migrations.RemoveField(
            model_name='dynamic',
            name='price1',
        ),
        migrations.RemoveField(
            model_name='dynamic',
            name='price2',
        ),
    ]
