# Generated by Django 4.2.3 on 2023-09-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0006_delete_package1_remove_dynamic_pkg1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewHotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='viewhotels')),
                ('img1', models.ImageField(upload_to='viewhotels')),
                ('img2', models.ImageField(upload_to='viewhotels')),
                ('name', models.CharField(max_length=100)),
                ('name1', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('hotelname', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('desc1', models.TextField()),
                ('desc2', models.TextField()),
                ('review', models.TextField()),
                ('review1', models.TextField()),
                ('review2', models.TextField()),
                ('rating', models.PositiveIntegerField()),
                ('rating1', models.PositiveIntegerField()),
                ('rating2', models.PositiveIntegerField()),
                ('price', models.IntegerField()),
                ('price1', models.IntegerField()),
                ('price2', models.IntegerField()),
            ],
        ),
    ]
