# Generated by Django 4.2.3 on 2023-09-19 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0007_viewhotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='explore.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='explore.packages'),
            preserve_default=False,
        ),
    ]
