# Generated by Django 4.2.3 on 2023-09-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0008_booking_hotel_booking_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
