# Generated by Django 4.2.3 on 2023-09-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0010_remove_booking_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='package_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
