# Generated by Django 4.2.3 on 2023-09-20 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0011_hotel_hotel_id_packages_package_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='package',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_id',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='package_id',
        ),
    ]
