# Generated by Django 4.2.3 on 2023-09-25 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0013_booking_hotel_booking_package_packages_package_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='package_id',
        ),
    ]
