# Generated by Django 4.2.3 on 2023-10-29 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explore', '0016_remove_booking_status_delete_cancellation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='STATUS',
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
