# Generated by Django 4.2.3 on 2023-11-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0017_remove_booking_status_booking_user_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
