# Generated by Django 4.2.3 on 2023-11-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0018_remove_booking_status_remove_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
