# Generated by Django 4.2.3 on 2023-12-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0019_booking_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='license_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='owner',
            field=models.TextField(default='Unknown'),
        ),
    ]
