# Generated by Django 4.2.3 on 2023-12-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0021_approvalstatus_hotel_submitted_hotel_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending'),
        ),
    ]
