# Generated by Django 4.2.3 on 2023-12-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0022_alter_hotel_approval_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovalStatus',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='hotel',
            name='license_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
