# Generated by Django 4.2.3 on 2023-09-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminDestinations',
        ),
        migrations.DeleteModel(
            name='AdminHotel',
        ),
    ]
