# Generated by Django 4.2.3 on 2023-10-06 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intro', '0002_delete_admindestinations_delete_adminhotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloggs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('img', models.ImageField(upload_to='bloggs')),
                ('description', models.TextField()),
                ('head1', models.TextField()),
                ('para1', models.TextField()),
                ('head3', models.TextField()),
                ('para3', models.TextField()),
                ('para4', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
